---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 2048
  template:
    metadata:
      labels:
        app: 2048
    spec:
      containers:
      - name: 2048
        image: fadocker123/1234:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: 2048-service
spec:
  selector:
    app: 2048
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: NodePort

